### ISSUE TITLE
TM: is not making use of the vald flag.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#847]
During analysis of the data flow I recognised data of P15 had been read even when the valid flag was false. Call of the operator was in trackatlas component.

**Comment by BerndHekele** [comment]
Remark - I'm checking dat-flow.
It is possible the xtrange flow of information after level 2 is caused by confused data.

**Comment by JakobGartner** [comment]
OK,

is it possible that you see data in the body of MovementAuthrority while the valid flag of the same is false?
This is due to the fact that in the MA I did not provide a mechanism that forces those outputs to default, assuming they are only evaluated by the functions downstream when they see the valid flag.

I will change that now, even if it only helps to make it more readable...

**Comment by JakobGartner** [comment]
As discussed, the issue was more complex. I have pushed a first solution.

**Comment by BerndHekele** [comment]
Hi Jakob,
I started testing the correction and continue to document my results on this issue.
I still get wrong values from the operator, but I can also see reasonable information coming from the track:
![image](https://cloud.githubusercontent.com/assets/3288918/10691118/040c643a-7987-11e5-9314-7e1d56271879.png)


The conversion operator to the old values seems to be non-functional.

However, this detail is not so important - the data received in the trackatlas is according to the requirements of the track.

After reading data the output of the trackAtlas regarding MRSP looks fine:
![image](https://cloud.githubusercontent.com/assets/3288918/10691439/626c42dc-7989-11e5-8733-1c245347eab3.png)
I'm not familar with the MA:
![image](https://cloud.githubusercontent.com/assets/3288918/10691478/a4491626-7989-11e5-908e-ac2dacf26b42.png)

The behaviour of the model is changed now: we run into an emergency brake. Looks like MA is not receved at SDM.

I will continue to investigate in SDM now. If you want to join give me a call.

**Comment by BerndHekele** [comment]
Short addition: I can start the train again. Speed limit is 40 km/h. Representation at the DMI is faulty.

![image](https://cloud.githubusercontent.com/assets/3288918/10691652/0dd75b1a-798b-11e5-9159-d90dfaa4910d.png)

**Comment by stefan-karg** [comment]
Fixed
