### ISSUE TITLE
No Radio Messages from EVC?

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#878]
With the current HEAD I don't see any radio messages sent from the EVC -> RBC. Can someone confirm ? (@BerndHekele, @Farhangi)

BR
Johannes

**Comment by Farhangi** [comment]
Bernd is working to fix it. It will be corrected with the next commit by @BerndHekele .

br
peyman

**Comment by jokaICS** [comment]
@BerndHekele I see that you've pushed an update for this, but I still don't get radio messages from the EVC. However, I'm using Testbench_EnvSim::ROOT_Scripted instead of the standard ROOT_Integration. Does radio comm work for ROOT_Integration?

**Comment by BerndHekele** [comment]
The correction is now on Github.
(Peyman did the fix)

**Comment by jokaICS** [comment]
OK, ROOT_Integration and ROOT_IntegrationTCP work as expected. However, for ROOT_Scripted I still don't get any radio messages from the EVC (and I've verified that the balise telegrams are sent to the EVC), which is strange, since it uses the same EVC operator as the other integration nodes. Have there been any changes to the Toolbox lately?

**Comment by BerndHekele** [comment]
Is this problem still open.
I would like to tackle the item.

**Comment by jokaICS** [comment]
Yes, with the version from this morning I still don't get messages from the EVC. I'm currently working on integration with Stefan -- do you have time after our jour fixe?

**Comment by Farhangi** [comment]
the bug has been fixed.

**Comment by jokaICS** [comment]
Solved (the error was due to my track converter util, which ignored all but the first balise in a BG). Thanks for the support.
